{'TIME':2022-01-06 09:13:44,594,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/plan/actividades','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /plan/actividades}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 22, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
TypeError: plan_actividades() missing 1 required positional argument: 'p_cTipSer'
{'TIME':2022-01-06 09:26:29,894,'ADDRESS':'10.10.150.66','URL': 'http://10.10.110.13:8001/plan/actividades','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /plan/actividades}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 22, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 256, in plan_actividades
    ploads = {"CCODPLA": session["paData"]["CCODPLA"], "CCODUSU": "9999"}
KeyError: 'paData'
{'TIME':2022-01-06 09:26:33,503,'ADDRESS':'10.10.150.66','URL': 'http://10.10.110.13:8001/plan/actividades','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /plan/actividades}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 22, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 256, in plan_actividades
    ploads = {"CCODPLA": session["paData"]["CCODPLA"], "CCODUSU": "9999"}
KeyError: 'paData'
