{'TIME':2022-01-05 08:17:36,055,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/7','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/7}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 221, in agregarcie10
    laData = session["TMP"][pnIndice]
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:18:28,439,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/7','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/7}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 221, in agregarcie10
    laData = session["TMP"][pnIndice]
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:28:56,506,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/1','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/1}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 221, in agregarcie10
    @login_required
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:29:10,433,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/1','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/1}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 221, in agregarcie10
    @login_required
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:29:10,594,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/1','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/1}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 221, in agregarcie10
    @login_required
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:29:11,011,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/1','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/1}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 221, in agregarcie10
    @login_required
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:29:11,139,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/1','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/1}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 221, in agregarcie10
    @login_required
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:29:56,456,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/1','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/1}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 228, in agregarcie10
    for laFila in session["paCie10"]:
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:31:56,444,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/1','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/1}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 228, in agregarcie10
    for laFila in session["paCie10"]:
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:34:02,659,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/11','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/11}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 228, in agregarcie10
    for laFila in session["paCie10"]:
TypeError: 'NoneType' object is not iterable
{'TIME':2022-01-05 08:35:37,743,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/agregar/cie10/11','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /agregar/cie10/11}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\decorators.py", line 11, in secure_function
    return func(*args, **kwargs)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 231, in agregarcie10
    session["paCie10"].append(laData)
AttributeError: 'NoneType' object has no attribute 'append'
