{'TIME':2022-01-07 08:24:32,392,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/act_ray','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /act_ray}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'Actividad.route_act' did not return a valid response. The function either returned None or ended without a return statement.
{'TIME':2022-01-07 08:26:03,094,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/act_ray','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /act_ray}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'Actividad.route_act' did not return a valid response. The function either returned None or ended without a return statement.
{'TIME':2022-01-07 08:26:05,904,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/act_ray','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /act_ray}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'Actividad.route_act' did not return a valid response. The function either returned None or ended without a return statement.
{'TIME':2022-01-07 08:27:20,768,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/act_ray','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /act_ray}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'Actividad.route_act' did not return a valid response. The function either returned None or ended without a return statement.
{'TIME':2022-01-07 08:28:36,291,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/act_ray','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /act_ray}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'Actividad.route_act' did not return a valid response. The function either returned None or ended without a return statement.
{'TIME':2022-01-07 08:29:27,979,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/act_ray','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /act_ray}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'Actividad.route_act' did not return a valid response. The function either returned None or ended without a return statement.
{'TIME':2022-01-07 08:30:01,707,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/act_ray','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /act_ray}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskSecurity\app\src\Actividad.py", line 68, in route_act
    redirect(url_for("Actividad.actividades"))
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'Actividad.actividades'. Did you forget to specify values ['p_cTipSer']?
{'TIME':2022-01-07 08:31:49,862,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/act_ray','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /act_ray}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'Actividad.route_act' did not return a valid response. The function either returned None or ended without a return statement.
{'TIME':2022-01-07 08:32:21,319,'ADDRESS':'127.0.0.1','URL': 'http://localhost:8001/act_ray','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /act_ray}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'Actividad.route_act' did not return a valid response. The function either returned None or ended without a return statement.
